export const EVENT_CONFIG = {
  name: "Boda de Jans Narvaez y Yurleydi Solarte",
  shortName: "Jans & Yurleydi",
  slogan: "Unidos bajo la gracia de Dios",
  biblicalReference: "Marcos 10:9",
  startDate: "2026-10-11T18:00:00-05:00",
  endDate: "2026-10-11T23:59:00-05:00",
  displayDate: "11 de octubre de 2026",
  venue: "Iglesia Pentecostal Unida de Colombia · Sede 4",
  address: "Barrio San Agustín",
  addressLine1: "Iglesia Pentecostal Unida de Colombia · Sede 4, Barrio San Agustín",
  addressLine2: "Mocoa, Putumayo, Colombia",
  city: "Mocoa, Putumayo",
  capacity: process.env.EVENT_CAPACITY ? Number(process.env.EVENT_CAPACITY) : null,
  mapsUrl: process.env.MAPS_URL ?? "https://www.google.com/maps/search/?api=1&query=Iglesia%20Pentecostal%20Unida%20de%20Colombia%20Sede%204%2C%20Barrio%20San%20Agustin%2C%20Mocoa%2C%20Putumayo",
  whatsappUrl: process.env.WHATSAPP_URL ?? "",
  organizerWhatsapp: "573000000000",
  wallpaper: "/wedding/jans-yurleydi-hero.jpeg",
  poster: "/wedding/jans-yurleydi-ceremony.jpeg",
} as const;

export const EVENT_JSON_LD = {
  "@context": "https://schema.org",
  "@type": "Event",
  name: EVENT_CONFIG.name,
  startDate: EVENT_CONFIG.startDate,
  endDate: EVENT_CONFIG.endDate,
  eventAttendanceMode: "https://schema.org/OfflineEventAttendanceMode",
  eventStatus: "https://schema.org/EventScheduled",
  location: {
    "@type": "Place",
    name: EVENT_CONFIG.venue,
    address: {
      "@type": "PostalAddress",
      addressLocality: "Mocoa",
      addressRegion: "Putumayo",
      addressCountry: "CO",
    },
  },
  image: [EVENT_CONFIG.wallpaper, EVENT_CONFIG.poster],
  description: "Invitación a la boda de Jans Narvaez y Yurleydi Solarte, el 11 de octubre de 2026 a las 6:00 p. m. en Mocoa, Putumayo.",
};
